name: Generate Docs

on:
  workflow_dispatch:

jobs:
  update-wiki:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: dev

      - name: Install .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Restore
        run: dotnet restore .\src\uWidgets.sln

      - name: Build
        run: dotnet build .\src\uWidgets.sln --configuration Release --no-restore

      - name: Install tool
        run: dotnet tool install -g XMLDoc2Markdown

      - name: Run tool
        run: |
          xmldoc2md .\src\uWidgets.Core\bin\Release\net8.0\uWidgets.Core.dll `
          --output .\wiki\API `
          --github-pages

      - name: Publish to wiki
        uses: Andrew-Chen-Wang/github-wiki-action@v4
