name: Generate Docs

on:
  workflow_dispatch:

jobs:
  update-wiki:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: dev

      - name: Install .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Install tool
        run: dotnet tool install -g XMLDoc2Markdown

      - name: Restore
        run: dotnet restore .\src\uWidgets.sln

      - name: Build
        run: dotnet build .\src\uWidgets.sln --configuration Release --no-restore

      - name: Run tool
        run: |
          xmldoc2md .\src\uWidgets.Core\bin\Release\net8.0\uWidgets.Core.dll `
          --output .\new-wiki\API `
          --github-pages `
          --index-page-name API `

      - name: Checkout wiki repository
        uses: actions/checkout@v4
        with:
          repository: ${{github.repository}}.wiki
          path: wiki
  
      - name: Update API docs
        run: |
          if (Test-Path -Path wiki\API) { Remove-Item -Recurse -Force wiki\API }
          New-Item -ItemType Directory -Path wiki\API
          Copy-Item -Path new-wiki\API\* -Destination wiki\API -Recurse

      - name: Commit & Push changes
        run: |
          cd wiki
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update API docs"
          git push
